melee_dps_weapons = [
    "1h Dagger",
    "Dagger Pair",
    "Claws",
    "Bloodletter",
    "Demonfang",
    "Deathgivers",
    "Bridled Fury",
    "1h Spear",
    "Pike",
    "Glaive",
    "Heron Spear",
    "Spirithunter",
    "Trinity Spear",
    "Dawnbreaker",
    "Broadsword",
    "Claymore",
    "Dual Swords",
    "Clarent Blade",
    "Carving Sword",
    "Galatine Pair",
    "Kingmaker",
    "Battleaxe",
    "Greataxe",
    "Halberd",
    "Carrioncaller",
    "Infernal Scythe",
    "Bear Paws",
    "Realmbreaker"
]
