ranged_dps_weapons = [
    "1h Fire Staff",
    "Great Fire Staff",
    "Infernal Staff",
    "Wildfire Staff",
    "Brimstone Staff",
    "Blazing Staff",
    "Dawnsong",
    "1h Frost Staff",
    "Great Frost Staff",
    "Glacial Staff",
    "Hoarfrost Staff",
    "Icicle Staff",
    "Permafrost Prism",
    "Chillhowl",
    "1h Cursed Staff",
    "Great Cursed Staff",
    "Demonic Staff",
    "Lifecurse Staff",
    "Cursed Skull",
    "Damnation Staff",
    "Shadowcaller",
    "Bow",
    "Warbow",
    "Longbow",
    "Whispering Bow",
    "Wailing Bow",
    "Bow of Badon",
    "Mistpiercer",
    "1h Crossbow",
    "Heavy Crossbow",
    "Light Crossbow",
    "Weeping Repeater",
    "Boltcasters",
    "Siegebow",
    "Energy Shaper"
]
