tank_weapons = [
    "1h Mace",
    "Heavy Mace",
    "Morning Star",
    "Bedrock Mace",
    "Incubus Mace",
    "Camlann Mace",
    "1h Hammer",
    "Polehammer",
    "Great Hammer",
    "Tombhammer",
    "Forge Hammers",
    "Grovekeeper",
    "Oathkeepers",
    "Hammer of Justice",
    "Grailseeker",
    "Quarterstaff",
    "Iron-Clad Staff",
    "Double Bladed Staff",
    "Black Monk Stave",
    "Soulscythe",
    "Staff of Balance"
]
